---
- name: Config mgr
  shell: ceph mgr module enable dashboard ; ceph dashboard create-self-signed-cert

- name: Set mgr
  shell: ceph config set mgr mgr/dashboard/{{ mgr }}/server_addr {{ ansible_default_ipv4.address }} ; ceph config set mgr mgr/dashboard/{{ mgr }}/server_port {{ mgr_port }} ; ceph dashboard set-login-credentials root {{ mgr_passwd }}

- name: Restart mgr service
  service: name= ceph-mgr@{{ mgr }} state=restarted 

- name: Cfg_mgr
  shell: ceph mgr services | grep "dashboard" | awk -F'"' '{ print $4}' 
  register: cfg_mgr

- name: Notice
  debug: msg="Ceph dashboard--- dashboard:{{ cfg_mgr.stdout }}  user:root  password:{{ mgr_passwd }}"

