---
#-name: Set hostname
#  hostname: name={{ nodename }}

- name: Install ntp,yum-plugin-priorities,epel-release--centos
  yum: name=ntp,epel-release state=latest
  when: ansible_distribution == "CentOS"

- name: Install ntp and epel-release--ubuntu
  apt: name=ntp,epel-release state=latest
  when: ansible_distribution == "Ubuntu"

- name: update server time 
  shell: ntpdate pool.ntp.org;systemctl restart ntpd;systemctl enable ntpd

- name: close firewalld and selinux
  shell: systemctl stop firewalld;systemctl disable firewalld ; setenforce 0 ; sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/sysconfig/selinux
  when: ansible_distribution == "CentOS"
